Geet/Project/Geet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', views.HomePage.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'community/',include("community.urls", namespace="community")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Geet/Project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.registration, name="signup"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"), #submit email in form
    path('password_reset/done/',auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),  # link sent to email to reset pw
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),  #present a form to enter new pw
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),  # pw succesfully change msg
    path('upload/', views.upload, name="upload"),
    path('startlistening/<int:id>/', views.player, name="player"),    
    path('startlistening/', views.startlistening, name="startlistening"),
    path('channel/',views.channel,name="channel"),
    path('', views.index, name="home"),
    path('community/', views.community, name="community"),
  
    path('listenlater/', views.listenlater , name="listenlater"),
    path('history/',views.history ,name='history'),
    path('search/',views.search ,name='search'),

]

Geet/Project/community/urls.py
from django.urls import path
from .import views


app_name='community'

urlpatterns=[
    
    path('post/', views.Post_list, name='post'),
    path('post/tag/<slug:tag_slug>',views.Post_list, name='post_list_by_tag'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('post/create/',views.Postcreateview.as_view(),name='create-post'),
    path('post/create/<int:id>',views.sharing,name='create-post'),
    path('post/<int:pk>/update/',views.Postupdateview.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
]

Geet/Project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from community.models import Postmodel

# Create your models here.
class Song(models.Model):
    song_id=models.AutoField(primary_key=True)
    song_name=models.CharField(max_length=1000)
    singer_name=models.CharField(max_length=1000)
    image=models.ImageField(upload_to='documents/')
    song_genre = models.CharField(max_length=1000, default="")
    song = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.song_name


class Listenlater(models.Model):
    listen_id=models. AutoField (primary_key=True)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    later_id = models. CharField(max_length=10000000, default="")
    added_at = models.DateTimeField(auto_now_add=True)


class History(models.Model):
    history_id =models. AutoField (primary_key=True)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    music_id = models. CharField(max_length=10000000, default="")
    done_at = models.DateTimeField(auto_now_add=True)

Geet/Project/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

Geet/Project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUser
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib.auth.decorators import login_required
from django.db.models import Case, When,Q

# Create your views here.

@login_required(login_url='/accounts/login/')
def index(request):
    song = Song.objects.all()
    return render(request, 'index.html', {'song':song})

def listenlater(request):
    
    if request.method== "POST":
        user=request.user
        later_id=request.POST['later_id']
        
        
        listen= Listenlater.objects.filter(user=user)

        for i in listen:

            if later_id== i.later_id:
                message= "Your Song is already added"
                break
        else:
            watchlater = Listenlater(user=user, later_id = later_id)
            watchlater.save()
            message="Your Song is successfuly added"
        
        song = Song.objects.filter(song_id=later_id).first()
        return render(request, f"accounts/player.html", {'song': song, "message": message})
    
    wl=Listenlater.objects.filter(user=request.user).order_by('-added_at')
    ids=[]
    for i in wl:
        ids.append(i.later_id)
        
    preserved = Case(*[When(pk=pk, then= pos) for pos, pk in enumerate(ids)])
    song= Song.objects.filter(song_id__in=ids).order_by(preserved)

    return render(request, "accounts/listenlater.html", {'song': song})

def upload(request):
        if request.method=="POST":
            song_name=request.POST["Song name"]
            singer_name=request.POST["Singer"]
            genre = request.POST["Genre"]
            songs = request.FILES["InputFile"]
            image= request.FILES["InputImage"]
            song_model = Song(song_name=song_name, singer_name=singer_name, song_genre=genre, image=image, song=songs)
            song_model.save()
        return render(request, 'accounts/upload.html')

def startlistening(request):
    song = Song.objects.all()
    return render(request, 'accounts/startlistening.html',{'song':song})

def player(request, id):
    song = Song.objects.filter(song_id = id).first()
    return render(request, 'accounts/player.html',{'song':song})

def registration(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUser()
        if request.method == 'POST':
            form = CreateUser(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {'form': form}
        return render(request, 'accounts/signup.html', context)


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')

def channel(request):
        
    history=History.objects.filter(user=request.user).order_by('-done_at')
    H=[]
    for i in history:
        H.append(i.music_id)
    
    preserved = Case(*[When(pk=pk, then= pos) for pos, pk in enumerate(H)])
    Hsong= Song.objects.filter(song_id__in=H).order_by(preserved)
    
    
   
    return render(request, "accounts/channel.html",{'song':Hsong},)

def history(request):
    if request.method== "POST":
        user=request.user
        music_id=request.POST['music_id']
        history = History(user=user, music_id = music_id)
        history.save()
        
        return redirect(f"/accounts/startlistening/{music_id}")
    
    history=History.objects.filter(user=request.user).order_by('-done_at')
    H=[]
    for i in history:
        H.append(i.music_id)
    
    preserved = Case(*[When(pk=pk, then= pos) for pos, pk in enumerate(H)])
    song= Song.objects.filter(song_id__in=H).order_by(preserved)

    return render(request, 'accounts/history.html',{'song':song})


def search(request):
    if request.method=="POST":
        searched = request.POST['searched']
        song=Song.objects.filter(song_name__iexact =searched)

        return render(request, 'accounts/search.html',{'searched':searched,'song':song})
    else:
        return render(request, 'accounts/search.html')
def community(request):
    return render(request, 'accounts/community.html')

Geet/Project/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <title>Geet</title>
        <link rel="stylesheet" href="{% static 'Geet/base.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/styles.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/startlistening.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/upload.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/player.css' %}">
       <link rel="stylesheet" href="{% static 'Geet/listenlater.css' %}">
       <link rel="stylesheet" href="{% static 'files/post.css' %}">  
       <link rel="stylesheet" href="{% static 'files/postdetail.css' %}">  
       <link rel="stylesheet" href="{% static 'files/postmodel.css' %}">  
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    
    <body>
        
        <div class="navbar">
                <img src = "{% static 'Geet/logo.png' %}" class = "logo">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:startlistening' %}">Start Listening</a></li>
                    <li><a href="{% url 'accounts:upload' %}">Upload</a></li>
                    <li><a href="{% url 'community:post' %}">Community</a></li>
                    {% if not user.is_authenticated %}
                    <li class = "dropdown"><button class="dropbtn">Connect</button>
                        <div class = "dropdown-content">
                            <a href="{% url 'accounts:login'%}">Log In</a>
                            <a href="{% url 'accounts:signup'%}">Sign Up</a>
  
                    </li> 
                    {% endif %}
                <li class = "dropdown1">
                    {% if user.is_authenticated %}
                    {% comment %} <img src = "{% static 'Geet/Profile.png' %}" class = "Userimage"> {% endcomment %}
                    <button onclick="myFunction()" class="dropbtn1">Hello, {{request.user}}</button>
                    <div id="myDropdown" class = "dropdown-content1">
                          <a  class="logout" href="{% url 'logout' %}">Logout</a>
                          <a class="dropdown-item" href="/accounts/listenlater/">Listen Later</a>
                          <a class="dropdown-item" href="/accounts/history/">Music History</a>
                          <a class="channel" href="{% url 'accounts:channel' %}">Your Channel</a>

                    </div>

                    {% endif %}


                </li>
                </ul>
            </div>
 {% block content %}

 {% endblock %}
           
    <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            // Close the dropdown if the user clicks outside of it
            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>
</html>

Geet/Project/accounts/templates/accounts/channel.html
{% extends "accounts/base.html" %}

{%  block content %}
<div class="container3">
    <div class="heading">{{request.user}}</div>
    <div class="subheading">Your Listen Later</div>
        {% for i in song  %}
        <div class = "box">
           
          <form action="/accounts/history/" id="his"method="POST" >{% csrf_token %}
            <input type="hidden" name="music_id" value={{i.song_id}} >
            <a href="/accounts/startlistening/{{i.song_id}}"><button class="textOverImage2" style="background-image:url({{i.image.url}})" 
            data-title="{{i.song_name}}" data-text="{{i.singer_name}} ">
            </button>
            </a>
        </form >
        {% endfor %}
    
    


</div>

{% endblock %}

Geet/Project/accounts/templates/accounts/history.html
{% extends "accounts/base.html" %}

{%  block content %}

  <body>
     <div class="container3">
            <div class="heading">History</div>
                
            <div class="music-container">
                {% if song|length < 1 %}
                  <h1>History is Empty.</h1>
                {% endif %}

                {% for i in song  %}
                <div class = "box">
                  <form action="/accounts/history/" id="his"method="POST" >{% csrf_token %}
                    <input type="hidden" name="music_id" value={{i.song_id}} >
                    <a href="/accounts/startlistening/{{i.song_id}}"><button class="textOverImage" style="background-image:url({{i.image.url}})" 
                    data-title="{{i.song_name}}" data-text="{{i.singer_name}} ">
                    </button>
                    </a>
                </form >
                {% endfor %}
                </div>
              </div>
        <script>
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>
    

  {% endblock %}

Geet/Project/accounts/templates/accounts/listenlater.html
{% extends "accounts/base.html" %}

{%  block content %}

  <body>   
     <div class="container">
            <div class="heading">listen later</div>

            <div class="music-container">
              {% if song|length < 1 %}
                  <h1>Listen Later is Empty.</h1>
                  {% endif %}

        {% for i in song reversed %}
            <div class="box">
                <div class="image">
                    <img src="{{i.image.url}}">
                </div>
                <div class="name">
                    {{i.singer_name}} - {{i.song_name}}
                </div>
                <div class="music">
                 <audio controls>
                 <source src="{{i.song.url}}" type="audio/mpeg">
                 </audio>
                 <div class="row">
                     {%if user.is_authenticated%}
                        <form action="/accounts/history/" method="POST">{% csrf_token %}
                            <input type="hidden" name="music_id" value={{i.song_id}}>
                            <a  href="/accounts/startlistening/{{i.song_id}}"><button class="btn btn-primary"style="margin-left: 2%; margin-top:1%" >Listen Song</button></a>
                        </form>
                    {%else%}
                    <a href="/accounts/startlistening/{{i.song_id}}"><button class="btn btn-primary"style="margin-left: 2%; margin-top:1%" >Listen Song</button></a>
                    {%endif%}
                    </div>
                </div>
            </div>
        {% endfor %}

            </div>
        </div>
        <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            // Close the dropdown if the user clicks outside of it
            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>

  {% endblock %}

Geet/Project/accounts/templates/accounts/login.html
<!DOCTYPE html>
{%load static%}
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'Geet/login.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<style>
	body,
	html {
		margin: 0;
		padding: 0;
		height: 100%;
		background: rgba(178,219,213, 0.3) !important;
		font-family: 'Poppins', sans-serif;
	}
	.user_card {
		width: 350px;
		margin-top: auto;
		margin-bottom: auto;
		background: #fff;
		position: relative;
		display: flex;
		justify-content: center;
		flex-direction: column;
		padding: 10px;
		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
		border-radius: 5px;

	}

	.form_container {
		margin-top: 20px;
	}

	#form-title{
		font-size: 25px;
		font-weight:500;
		color: #40978a;
	}

	.login_btn {
		width: 100%;
		background: #1e9b88 !important;
		color: white !important;
	}

	.login_btn:hover{
		background:#5ebdae;
	}

	.login_btn:focus {
		box-shadow: none !important;
		outline: 0px !important;
	}
	.login_container {
		padding: 0 2rem;
	}
	.input-group-text {
		background: #42958e !important;
		color: white !important;
		border: 0 !important;
		border-radius: 0.25rem 0 0 0.25rem !important;
	}
	.input_user,
	.input_pass:focus {
		box-shadow: none !important;
		outline: 0px !important;
	}

	#messages{
		background-color: grey;
		color: #fff;
		padding: 10px;
		margin-top: 10px;
	}
	.ml-1{
		padding-top:6px;
	}
</style>
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
				<div class="d-flex justify-content-center links">
				   <a href="{% url 'accounts:password_reset' %}" class="ml-1">Forgot Password?</a>
                </div>
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

Geet/Project/accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}


{% block content %}

	{% load crispy_forms_tags %}          

	<!--Reset Password-->
	<div style = "padding: 15px;" class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
			<div style="padding-top: 15px" class = "input-field">
                    <label>Email</label>
                    <input style="height:30px; width:200px; margin-left: 10px;" type="email" class ="input" name="email" placeholder="Enter your Email">
                </div>      
            <button style="height:30px; width:150px;" class="btn btn-primary" type="submit">Send email</button>
        </form>
  	</div> 

{% endblock %}

Geet/Project/accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}

{% block content %} 
  
  <!--Password Reset Complete-->
    <div style = "padding: 15px;" class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

Geet/Project/accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}

{% block content %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

Geet/Project/accounts/templates/accounts/password_reset_sent.html
{% extends 'accounts/base.html' %}


{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            <br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

Geet/Project/accounts/templates/accounts/player.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}
{% if message %}
<script>

 Swal.fire({
     position: 'top-end',
     icon: 'success',
     title: '{{message}}',
     showConfirmButton: false,
     timer: 1500
 }) 
</script>
{% endif %}

<div class="whole">
  <div class="main">
  	<p id="logo"><i class="fa fa-music"></i>Music</p>
 
     <div class="left">
      <img id="track_image" src = "{{song.image.url}}">
         <div class="volume">
            <p id="volume_show">90</p>
            <i class="fa fa-volume-up" aria-hidden="true" id="volume_icon"></i>
            <input type="range" min="0" max="100" value="90" onchange="volume_change()" id="volume">  
         </div>

     </div>
 

  	 <div class="right">

      <p id="title">{{song.song_name}}</p>
      <p id="artist">{{song.singer_name}}</p>
   
  	 	<div class="middle">
  	       <button onclick="previous_song()" id="pre"><i class="fa fa-step-backward" aria-hidden="true"></i></button>
      	   <button id="ppicon"><i class="fa fa-play" aria-hidden="true"></i></button>
  	       <button onclick="next_song()" id="next"><a href="/accounts/startlistening/{{song.song_id}}/"><i class="fa fa-step-forward" aria-hidden="true"></i></button>
  	   </div>


        <div class="duration">
           <input type="range" min="0" max="100" value="0" id="duration_slider" onchange="change_duration()" >
        </div>
          
           <div>
              {% if user.is_authenticated %} 
            <form action="/accounts/listenlater/" method="POST">{% csrf_token %}
                <input type="hidden" name="later_id" value="{{song.song_id}}">
                <button type="submit" class="listenlater" style="margin-left: 2%;">Add to Listen Later</button>
                <button type="submit" class="sharing" style="margin-left: 2%;"><a href="/community/post/create/">Share</a></button>

             </form>  
             {% endif %}
           </div>
           
  	</div>

  </div>
</div>   
  <audio id = "mysong" metadata>
   <source src = "{{song.song.url}}" type = "audio/mp3">
   </audio>

<script>
let recent_volume= document.querySelector('#volume');
let slider = document.querySelector('#duration_slider');
let mysong = document.querySelector('#mysong');
var ppicon = document.getElementById('ppicon');
var volume_icon = document.getElementById('volume_icon');
timer = setInterval(range_slider ,1000);



    ppicon.onclick = function()
   {
     if(mysong.paused)
     {
        mysong.play();
        ppicon.innerHTML = '<i class="fa fa-pause" aria-hidden="true"></i>';
     }
     else{
        mysong.pause();
        ppicon.innerHTML = '<i class="fa fa-play" aria-hidden="true"></i>';
     }
   } 

   volume_icon.onclick = function()
   {
      mysong.volume = 0;
	   volume.value = 0;
	   volume_show.innerHTML = 0;
   }

   function volume_change(){
	   volume_show.innerHTML = recent_volume.value;
	   mysong.volume = recent_volume.value / 100; 
      
   }
    
    function change_duration(){
      mysong.currentTime = mysong.duration * (slider.value / 100);
      console.log(mysong.duration * (slider.value / 100));
      console.log(mysong.currentTime);
   } 

   function range_slider(){
	let position = 0;
        
		if(!isNaN(mysong.duration)){
		   slider_position = mysong.currentTime * (100 / mysong.duration);
		   slider.value =  slider_position;
        
	      }     

      if(mysong.ended){
       	 play.innerHTML = '<i class="fa fa-play" aria-hidden="true"></i>'; 
      }
     }

   
</script>

{% endblock %}

Geet/Project/accounts/templates/accounts/search.html
{% extends "accounts/base.html" %}

{%  block content %}
<centre>
    {%if searched%}
        <div class="heading">You searched for {{searched}}</div>
        <br/>
        {% for i in song reversed %}
        <div class = "box">
        {% if user.is_authenticated %}
        <form action="/accounts/history/" id="his"method="POST" >{% csrf_token %}
            <input type="hidden" name="music_id" value={{i.song_id}} >
            <a href="/accounts/startlistening/{{i.song_id}}"><button class="textOverImage" style="background-image:url({{i.image.url}})" 
            data-title="{{i.song_name}}" data-text="{{i.singer_name}} ">
            </button>
            </a>
        </form >
        {%else%}
        <a href="/accounts/startlistening/{{i.song_id}}" class="textOverImage" style="background-image:url({{i.image.url}})"
        data-title="{{i.song_name}}" data-text="{{i.singer_name}} "></a>
        {%endif%}
        
        </div>
        {% endfor %}
    {%else%}
        <div class="heading">You didn't search</div>
    {%endif%}
</centre>
{%endblock%}

Geet/Project/accounts/templates/accounts/startlistening.html
{% extends "accounts/base.html" %}
{% load static %}

{%  block content %}

        <div class="heading">Start Listening</div>
     <div class="container3">
        <div class="searchbar">
                <form class="d-flex" method="POST"action="/accounts/search/">{%csrf_token%}
                        <input class="sharing" type="search" placeholder=" search" aria-label="search" name="searched">
                        <button class = "btn" style="width: 100px; height: 30px" type="submit">Search</button>
                </form>
        
        </div>
        {% for i in song reversed %}
        <div class = "box">
        {% if user.is_authenticated %}
        <form action="/accounts/history/" id="his"method="POST" >{% csrf_token %}
            <input type="hidden" name="music_id" value={{i.song_id}} >
            <a href="/accounts/startlistening/{{i.song_id}}"><button class="textOverImage" style="background-image:url({{i.image.url}})" 
            data-title="{{i.song_name}}" data-text="{{i.singer_name}} ">
            </button>
            </a>
        </form >
        {%else%}
        <a href="/accounts/startlistening/{{i.song_id}}" class="textOverImage" style="background-image:url({{i.image.url}})"
        data-title="{{i.song_name}}" data-text="{{i.singer_name}} "></a>
        {%endif%}
        
        </div>
        {% endfor %}
     </div>
        <script>
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>
   

    

  {% endblock %}