Geet/Project/Geet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', views.HomePage.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'community/',include("community.urls", namespace="community")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Geet/Project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.registration, name="signup"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"), #submit email in form
    path('password_reset/done/',auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),  # link sent to email to reset pw
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),  #present a form to enter new pw
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),  # pw succesfully change msg
    path('upload/', views.upload, name="upload"),
    path('startlistening/<int:id>/', views.player, name="player"),    
    path('startlistening/', views.startlistening, name="startlistening"),
    path('channel/',views.channel,name="channel"),
    path('', views.index, name="home"),
    path('community/', views.community, name="community"),
  
    path('listenlater/', views.listenlater , name="listenlater"),
    path('history/',views.history ,name='history'),
    path('search/',views.search ,name='search'),

]

Geet/Project/community/urls.py
from django.urls import path
from .import views


app_name='community'

urlpatterns=[
    
    path('post/', views.Post_list, name='post'),
    path('post/tag/<slug:tag_slug>',views.Post_list, name='post_list_by_tag'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('post/create/',views.Postcreateview.as_view(),name='create-post'),
    path('post/create/<int:id>',views.sharing,name='create-post'),
    path('post/<int:pk>/update/',views.Postupdateview.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
]

Geet/Project/community/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models import Manager
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager


# Create your models here.

class Querymanager(models.Manager):
    def get_queryset(self):
        return super(Querymanager, self).get_queryset().filter(status='published')


class Postmodel(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),
                      )

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique_for_date='publish', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=CASCADE, related_name='author_posts')
    body = models.TextField()
    image = models.ImageField(upload_to='images')
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")
    object = models.Manager()
    published = Querymanager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('community:post_detail',
                            kwargs={'pk': self.pk})

         #class meta:

    #    ordering = ('-publish',)  # sort post according to the publish date

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Postmodel, self).save(*args, **kwargs)


class comment(models.Model):
    post=models.ForeignKey(Postmodel,on_delete=models.CASCADE,related_name='comments')
    user= models.ForeignKey(User,on_delete=models.CASCADE,default=True)
    email=models.EmailField()
    body=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class meta:
        ordering = 'created'

    def __str__(self):
        return f'comment by {self.user} on {self.post}'

Geet/Project/community/forms.py
from django.contrib.auth.models import User
from .models import comment
from django import forms                                   # we need form to submit anything in our page

class EmailForm(forms.Form):
    name=forms.CharField(max_length=30)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ['email','body',]   

Geet/Project/community/views.py
from django.core import paginator
from django.forms.forms import Form
from django.shortcuts import get_object_or_404, render
from .models import *
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .forms import *
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import CreateView,UpdateView,DeleteView
from accounts.models import Song
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

def Post_list(request,tag_slug=None):
    object_list=Postmodel.published.all().order_by('-publish')
    tag=None

    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
    paginator=Paginator(object_list,5)
    page=request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,'community/post.html',{'page':page,'posts':posts,'tag':tag})


def post_detail(request,pk):
    post=get_object_or_404(Postmodel,id=pk) 
                     
    comments=post.comments.filter(active=True)         
    new_comment=None

    if request.method=='POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.user = request.user
            new_comment=comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        post_tags_ids = post.tags.values_list('id',flat=True)   # it returns id of post which have tags
        similar_posts=Postmodel.published.filter(tags__in =post_tags_ids.exclude(id=post.id))
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4] #Count gives the number of same tags belonging to each post

        comment_form = CommentForm()

    return render(request,'community/post_detail.html',{'post':post,'comments':comments,
                                                        'new_comment':new_comment,'comment_form':comment_form,
                                                        'similar_posts':similar_posts})   


class Postcreateview(LoginRequiredMixin,CreateView):
    model=Postmodel
    fields=['title','slug','body','tags','status']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

def sharing(request, id):
    model=Postmodel
    fields=['title','slug','body','tags','status']
    song = Song.objects.filter(song_id = id).first()
    return render(request, 'community/postmodel_form.html',{'song':song})

class Postupdateview(LoginRequiredMixin,UpdateView,UserPassesTestMixin):   # it allows you to define a test function which must return True
                                                                            #if the current user can access the view.
    model=Postmodel
    fields=['title','slug','body','tags','status']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()                  #if author and user are same then return true 
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(DeleteView,LoginRequiredMixin,UserPassesTestMixin):
    model=Postmodel
    success_url='/community/post'
 
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def post_share(request,post_id):
    post=get_object_or_404(Postmodel,id=post_id)
    sent = False
    if request.method== 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            #....it send email
            post_url= request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail=(subject,message,'adityakhadka907@gmai.com', cd['to'])
            sent = True
    else:
        form=EmailForm()
    return render (request,'community/post_share.html',{'post':post,'form':form,'sent':sent})        

Geet/Project/community/templates/community/base.html
{% extends 'accounts/base.html' %}
{% load posts_tags %}
<div class="content">
    {% block content %}

   
  
    {% endblock %}

Geet/Project/community/templates/community/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

Geet/Project/community/templates/community/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

Geet/Project/community/templates/community/post.html
{% extends 'community/base.html' %}
{% block title %}My Post {% endblock %}
{% load posts_tags %}
{% load static %}
{% load markdown_deux_tags %}
{% block content %}
<div class = "parent">
            <div class = "right_side">
            <h1>My Music Post</h1>
            
            </div>

            <div class = "left_side">
                <h1>Side Feed<h1>
            </div>
            {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
            {% endif %}
    <div class = "user_posts">
                {% for post in posts %}
                <h2>
                    <a class = "post_title" href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author }}
                </p>
                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url "community:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </p>
                
                {{ post.body| markdown |truncatewords:35 }}
                
                {% endfor %}
            
    </div>

     <div class="sidefeed">
    
        <p>There are total {% total_post %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}

        <h3>most commented posts</h3>
        {% get_most_commented_posts as most_commented_post %}
        <ul>
            {% for post in most_commented_post %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class = "divv4">
    {% include 'community/pagination.html' with page=posts %}
        <div class="createown">
             <label>Create your own post </label>
            <button type="submit" ><a class="newpost" href="{% url 'community:create-post' %}">Add post</a></button>
        </div>
    </div>
  </div>
{% endblock %}

Geet/Project/community/templates/community/post_detail.html
{% extends 'community/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% load markdown_deux_tags %}
{% load posts_tags %}
{% block content %}



<div class="parent1">
    <div class="div1" style = "color:#00abff;"> 
        <h1>{{ post.title }}</h1>
    </div>

    <div class="div2">
        <h1>Side Feed<h1>
    </div>

    <div class="div3"> 
    
        <p>There are total {% total_post %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}

        <h3>most commented posts</h3>
        {% get_most_commented_posts as most_commented_post %}
        <ul>
            {% for post in most_commented_post %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>


    <div class="div4"> 
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>

        {{ post.body|markdown }}  
        
        </p>

    </div>

{% if post.author == user %}
    <div class="div5"> 
        <button type="submit"><a href="{% url 'community:update-post' post.id %}">Update</a></button>
    </div>

    <div class="div6"> 
        <button type="submit"><a href="{% url 'community:post-delete' post.id %}">Delete</a></button>
    </div>
{% endif %}

    <div class="div7"> 
        <p><button type="submit" href="{% url 'community:post_share' post.id %}">share</button>
    </div>
    <div class="div8">
      <div class="similarpost">
        <h2>Similar Posts</h2>
        {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        There are no similar posts yet.
        {% endfor %}
        </div>
        {% for comment in comments %}

        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.user }} - {{ comment.created_at }}
        </p>
        {{ comment.body|markdown }}

        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %}

        {% if new_comment %}
        <h2>Your Comment has been added</h2>
        {% else %}
   

        {% if user.is_authenticated %}
       <div class = "mainbox">
                 <h2>Add a new Comment</h2>
            <form method="post">
                {% csrf_token %}
            <div class = "form">
                <div class = "input-field">
                    <label>Email</label>
                    <input style="height:30px; width:200px;" type="email" class ="input" name="email" placeholder="Enter your Email">
                </div>

                <div class = "input-field">
                    <label>Comment</label>
                    <textarea style="resize: none; height:100px; width:200px;" type="text" class ="input" name="body" placeholder="Enter your comment"></textarea>
                </div>

                <div class="input-field">
                    <button type="submit" class="btn">Add comment</button>
                </div>
                
            </div>
            
            </form>
       </div>
        {% else %}

        <p class="text-center">
        Only registered users can post comments. Please,
        <a href="{% url 'accounts:login' %}">login</a>.
        </p>
        {% endif %}

        {% endif %}
    </div>

</div>

{% endblock %}

Geet/Project/community/templates/community/post_share.html
{% extends "community/base.html" %}

{% block title %}Share a Post{% endblock %}
{% block content %}

{% if sent %}
  <h1>E-mail sent successfully</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
</p>
{% else %}
  <h1>Share "{{ post.title }}" by e-mail</h1>
  <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send E-Mail">
  </form>
{% endif %}
{% endblock %}

Geet/Project/community/templates/community/postmodel_confirm_delete.html
{% extends "community/base.html" %}
{% block title %}delete post{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="title">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}" ?</h2>
            
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'community:post_detail' object.id %}">Cancel</a>
            </div>
        </fieldset>
        </form>
    </div>
{% endblock content %}

Geet/Project/community/templates/community/postmodel_form.html
{% extends "community/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <legend class="title">Blog Post</legend>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              
              {{ form|crispy }}
          
          <div class="control-group">
              <button class="btn btn-outline-info" type="submit">Post</button>
          </div>
      </fieldset>
        </form>
    </div>
{% endblock content %}